apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- "https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref=v0.10.1"
resources:
- node-feature-rules.yaml
