apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: fpga-mutator-webhook-cfg
  labels:
    app: intel-fpga-webhook
webhooks:
- name: fpga.mutator.webhooks.intel.com
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  clientConfig:
    service:
      path: "/pods"
      namespace: default
      name: intel-fpga-webhook-svc
    caBundle: {CA_BUNDLE}
