qat:
  metadata:
    name: qatdeviceplugin-sample
  spec:
    image: intel/intel-qat-plugin:0.24.0
    initImage: intel/intel-qat-initcontainer:0.24.0
    dpdkDriver: vfio-pci
    kernelVfDrivers:
      - c6xxvf
      - 4xxxvf
    maxNumDevices: 128
    logLevel: 4
    nodeSelector:
      intel.feature.node.kubernetes.io/qat: 'true'
