# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by deployment/operator/default
resources:
- bases/deviceplugin.intel.com_gpudeviceplugins.yaml
- bases/deviceplugin.intel.com_qatdeviceplugins.yaml
- bases/deviceplugin.intel.com_fpgadeviceplugins.yaml
- bases/deviceplugin.intel.com_sgxdeviceplugins.yaml
- bases/fpga.intel.com_acceleratorfunctions.yaml
- bases/fpga.intel.com_fpgaregions.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- patches/webhook_in_gpudeviceplugins.yaml
- patches/webhook_in_qatdeviceplugins.yaml
- patches/webhook_in_fpgadeviceplugins.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_gpudeviceplugins.yaml
- patches/cainjection_in_qatdeviceplugins.yaml
- patches/cainjection_in_fpgadeviceplugins.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# TODO(rojkov): enable Prometheus

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
