name: e2e-qat
on:
  workflow_dispatch:
    inputs:
      images:
        description: 'Images to build before provisioning pull on worker'
        required: true
        default: 'intel-qat-plugin:devel crypto-perf:devel'

env:
  IMAGES: ${{ github.event.inputs.images }}

jobs:
  e2e-qat:
    name: e2e-qat
    #if: contains('["bart0sh"]', github.actor)
    runs-on: [self-hosted, linux, x64, qat]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Describe test environment
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Images: ${{ github.event.inputs.images }}"
      - name: Wait for ready state
        run: ../../../../bmetal/actions-bmetal-runstage.sh waitready
      - name: Prepare test environment
        run: ../../../../bmetal/actions-bmetal-runstage.sh prepare
      - name: Run tests
        run: ../../../../bmetal/actions-bmetal-runstage.sh test
